apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mconte
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:        
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/mconte-harbot-project/app@sha256:acab8fc2492f80e5fe7a0d1b786e216b0ef61b6a8c647d52a442869327fe54d3
        ports:
        - containerPort: 5000
